### PR TITLE
Add additional properties to the Item.

### PR DESCRIPTION
**Pull request by khiminrm**
Hi!

I've noticed that we can't set 'groupPackageCount'. It would be nice to have it. Please, merge, if everything looks correct. Thanks!

### CODE REVIEW

**Comment by code2prog** [comment]
@khiminrm Thank you for your contribution. I'll take a look at your suggested changes on Saturday morning.

**Comment by khiminrm** [comment]
@code2prog thanks! I've committed one more property. Please, take a look. 
I'm trying to use FedexRest to upgrade this module https://www.drupal.org/project/commerce_fedex to work with the FedEx Rest API.

**Comment by khiminrm** [comment]
I see that I might need to add another one - subPackagingType. Not sure maybe I will create separate MR. Just need to find out all possible values. 
BTW, I can't fully test the fixes in live mode. The virtualized responses from FedEx API not always work with additional params in the request's body.

**Comment by khiminrm** [comment]
I've committed subPackagingType class with constants and property for the Item.

**Comment by khiminrm** [comment]
have committed also the 'declaredValue' property

**Comment by khiminrm** [comment]
@code2prog Hi! I've question regarding Weight. Why FedexRest\Entity\Weight::setValue() uses integer argument and not float?

**Comment by khiminrm** [comment]
@code2prog  please, review the fixes. thanks!

**Comment by code2prog** [comment]
@khiminrm I will do it tonight. I'm having a hard time finding the time.
Thanks for your help

**Comment by khiminrm** [comment]
I've found one more thing which maybe would make sense to fix. The dimensions values should be integer values:
Знімок екрана 2024-02-05 о 16 25 37
Thoughts?

**Comment by code2prog** [comment]
@khiminrm If you include the change in the test and it passes it, I think it should be ok

**Review by code2prog — APPROVED** [review]
Looks good for me

**Comment by khiminrm** [comment]
@code2prog thanks!

**Comment by code2prog** [comment]
@khiminrm Thank you for your help!

**Pull request merged**
